export const maintenanceSuggestions = {
    cleaning: [
        "fullPlayfield",
        "bumpers",
        "flippers",
        "glass",
        "rails",
        "dusting",
        "sensors",
    ],
    repair: [
        "flippers",
        "mechanical",
        "electrical",
        "bumpers",
        "ramps",
        "plunger",
        "glass",
    ],
    replacement: [
        "balls",
        "leftFlipperCoil",
        "rightFlipperCoil",
        "solenoids",
        "switches",
        "leds",
        "springs",
        "belt",
        "vibrationMotor",
    ],
    upgrade: [
        "leds",
        "sound",
        "modernSensors",
        "lighting",
        "pinball",
        "plunger",
        "mechanical",
    ],
    inspection: [
        "general",
        "flippers",
        "bumpers",
        "electrical",
        "playfield",
        "sensors",
    ],
}
