export const Manufacturers: { [key: string]: string } = {
    "stern": "Stern",
    "jersey-jack-pinball": "Jersey Jack Pinball",
    "hexa-pinball": "HEXA Pinball",
    "spooky-pinball": "Spooky Pinball",
    "williams": "Williams",
    "bally": "Bally",
    "american-pinball": "American Pinball",
    "midway": "Midway",

    "aa-amusements": "A.A. Amusements",
    "ami": "A.M.I.",
    "achille-chalvignac": "Achille and Chalvignac",
    "alben": "Alben",
    "allied-leisure": "Allied Leisure",
    "alvin-g-and-co": "Alvin G. & Co",
    "american-girl": "American Girl",
    "apple-time": "Apple Time",
    "arkon": "Arkon",
    "astro-games": "Astro Games",
    "atari": "Atari",
    "automaticos": "Automaticos",
    "bandai-namco": "Bandai Namco",
    "barni": "Barni",
    "barrels-of-fun": "Barrels of Fun",
    "bell-coin-matic": "Bell Coin Matic",
    "bell-games": "Bell Games",
    "bigliardini-elettronici-milano": "Bigliardini Elettronici Milano",
    "block-marble-company": "Block Marble Company",
    "briarwood": "Briarwood",
    "brunswick": "Brunswick",
    "cea": "C.E.A.",
    "capcom": "Capcom",
    "chicago-coin": "Chicago Coin",
    "chicago-gaming": "Chicago Gaming",
    "cic-play": "Cic Play",
    "cisco": "Cisco",
    "coffee-mat": "Coffee Mat",
    "data-east": "Data East",
    "deeproot": "deeproot",
    "dpx": "DPX",
    "dutch-pinball": "Dutch Pinball",
    "elbos": "Elbos",
    "eric-priepke": "Eric Priepke",
    "europlay": "Europlay",
    "exhibit": "Exhibit",
    "fascination-game": "Fascination Game",
    "for-amusement-only": "For Amusement Only Games",
    "game-plan": "Game Plan",
    "geiger": "Geiger",
    "genco": "Genco",
    "giorgio-massiniero": "Giorgio Massiniero",
    "giuliano-lodola": "Giuliano Lodola",
    "gottlieb": "Gottlieb",
    "d-gottlieb-co": "Gottlieb",
    "grand-products": "Grand Products",
    "haggis-pinball": "Haggis Pinball",
    "hanilamatic": "Hanilamatic",
    "hankin": "Hankin",
    "heighway-pinball": "Heighway Pinball",

    "hispamatic": "Hispamatic",
    "homepin": "Homepin",
    "idi": "I.D.I.",
    "ian-harrower": "Ian Harrower Games",
    "idsa": "IDSA",
    "inder": "Inder",
    "ice": "Innovative Concepts (ICE)",
    "interflip": "Interflip",
    "international": "International",
    "j-esteban": "J. Esteban",
    "jac-van-ham": "Jac Van Ham",
    "jeutel": "Jeutel",
    "joctronic": "Joctronic",
    "juegos-populares": "Juegos Populares",
    "kc-tabart": "K.C. Tabart",
    "keeney": "Keeney",
    "komplett": "Komplett",
    "komputer-dynamics": "Komputer Dynamics",
    "ltd-brasil": "LTD do Brasil",
    "mac-pinball": "Maguinas / Mac Pinball",
    "mali": "Mali",
    "mambelli": "Mambelli",
    "maresa": "Maresa",
    "marsa-play": "Marsa Play",
    "marvel": "Marvel",
    "mattel": "Mattel",
    "megaverse": "Megaverse Project",
    "mike-budai": "Mike Budai",
    "mirco": "Mirco Games",
    "mocean": "Mocean",
    "mondialmatic": "Mondialmatic",
    "mr-game": "Mr Game",
    "multimorphic": "Multimorphic",
    "nordamatic": "Nordamatic",
    "north-star": "North Star",
    "nsm": "Nsm",
    "pedretti": "Pedretti Gaming",
    "petaco": "Petaco",
    "peyper": "Peyper",
    "pinball-adventures": "Pinball Adventures",
    "pinball-brothers": "Pinball Brothers",
    "pinball-mfg": "Pinball Manufacturing Inc.",
    "pinball-shop": "Pinball Shop",
    "pinnovating": "Pinnovating",
    "pinstar": "Pinstar",
    "playbar": "Playbar",
    "playmatic": "Playmatic",
    "playmec": "Playmec Flippers",
    "quetzal": "Quetzal Pinball",
    "rmg": "R.M.G.",
    "rally": "Rally",
    "ramps": "Ramp's Pinball",
    "rebellion": "Rebellion Pinball",
    "recel": "Recel",
    "recreativos-franco": "Recreativos Franco",
    "red-baron": "Red Baron Amusements",
    "retro-pinball": "Retro Pinball",
    "riot": "Riot Pinball",
    "sankyo": "Sankyo Seiki",
    "sega": "Sega",
    "segasa": "Segasa",
    "sentinel": "Sentinel",
    "sirmo": "SIRMO",
    "skit-b": "Skit-B Pinball",
    "sleic": "Sleic",
    "sonic": "Sonic",
    "spinball": "Spinball",
    "sportmatic": "Sportmatic",
    "staal": "Staal",
    "stern-electronics": "Stern Electronics",
    "suncoast": "Suncoast Pinball",
    "th-bergmann": "T.H. Bergmann",
    "taito": "Taito",
    "team-pinball": "Team Pinball",
    "tecnoplay": "Tecnoplay",
    "turner-pinball": "Turner Pinball",
    "unidesa": "Unidesa",
    "united": "United",
    "universal": "Universal",
    "unknown": "Unknown",
    "valley": "Valley",
    "vector": "Vector Pinball",
    "venture-line": "Venture Line",
    "videodens": "Videodens",
    "viza": "Viza Manufacturing",
    "whizbang": "WhizBang Pinball",
    "wico": "Wico",
    "zaccaria": "Zaccaria",
    "zidware": "Zidware"
};
