version: "3.9"

services:
    db:
        image: postgis/postgis:17-3.5
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - db_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"

volumes:
    db_data:

