export const featureLabels = {
    playfield: {
        flippers: "Flippers",
        popBumpers: "Pop Bumpers",
        slingshots: "Slingshots",
        ramps: "Ramps",
        rampsMotorisees: "Motorized Ramps",
        inlanes: "Inlanes",
        outlanes: "Outlanes",
        standUpTargets: "Stand-up Targets",
        dropTargets: "Drop Targets",
        rockerTargets: "Rocker Targets",
        spinners: "Spinners",
        captiveBall: "Captive Ball",
        kickoutHole: "Kickout Hole",
        saucers: "Saucers",
        scoops: "Scoops",
        ballLock: "Ball Lock",
        diverters: "Diverters",
        kickbacks: "Kickbacks",
        magnets: "Magnets",
        tunnels: "Tunnels",
        skillShotLane: "Skill Shot Lane",
        plunger: "Plunger",
        shakerMotor: "Shaker Motor",
        mechanicalToys: "Mechanical Toys",
        miniPlayfields: "Mini Playfields",
        dropTargetsEvolutifs: "Progressive Drop Targets",
    },
    game_modes: {
        multiball: "Multiball",
        missions: "Missions",
        wizardMode: "Wizard Mode",
        skillShots: "Skill Shots",
        combos: "Combos",
        progressionPersistante: "Progression Persistante",
        achievements: "Achievements",
        difficultyScaling: "Difficulty Scaling",
        timedModes: "Timed Modes",
        randomEvents: "Random Events",
        extraBall: "Extra Ball",
        replay: "Replay",
        playerProfiles: "Player Profiles",
        challengeMode: "Challenge Mode",
        tournamentMode: "Tournament Mode",
    },
    visual_feedback: {
        dotMatrixDisplay: "Dot Matrix Display",
        lcdTftDisplay: "LCD/TFT Display",
        scoreDisplays: "Score Displays",
        ledInserts: "LED Inserts",
        generalIllumination: "General Illumination",
        spotlights: "Spotlights",
        rgbLedsAdressables: "RGB LEDs Adressables",
        backglassEclaire: "Backglass Éclairé",
        lightShowsSynchronises: "Light Shows Synchronisés",
        hudOverlay: "HUD Overlay",
    },
    audio: {
        musique: "Musique",
        voiceSpeech: "Voice/Speech",
        soundEffects: "Sound Effects",
        digitizedSpeech: "Digitized Speech",
        multiChannelAudio: "Multi-channel Audio",
        dynamicMix: "Dynamic Mix",
        customPlaylists: "Custom Playlists",
        reactiveAudio: "Reactive Audio",
    },
    electronics: {
        cpuMpuBoard: "CPU/MPU Board",
        driverBoards: "Driver Boards",
        ioBoards: "I/O Boards",
        powerSupply: "Power Supply",
        fuseProtection: "Fuse Protection",
        tiltSensor: "Tilt Sensor",
        slamTilt: "Slam Tilt",
        switchMatrix: "Switch Matrix",
        opticalSensors: "Optical Sensors",
        hallSensors: "Hall Sensors",
        reedSwitches: "Reed Switches",
        solenoids: "Solenoids",
        pwmLeds: "PWM LEDs",
        soundBoard: "Sound Board",
        amplificateur: "Amplificateur",
        networkModule: "Network Module",
        usbSdSlot: "USB/SD Slot",
        remoteDiagnostics: "Remote Diagnostics",
        operatorMenu: "Operator Menu",
        firmwareUpdates: "Firmware Updates",
    },
    connectivity: {
        wiFi: "Wi-Fi",
        ethernet: "Ethernet",
        bluetooth: "Bluetooth",
        onlineLeaderboards: "Online Leaderboards",
        cloudSaves: "Cloud Saves",
        companionApp: "Companion App",
        tournamentModeOnline: "Tournament Mode Online",
        apiWebhooks: "API Webhooks",
        streamingFeatures: "Streaming Features",
    },
    cabinet: {
        plasticsDecoratifs: "Plastics Décoratifs",
        transliteBackglass: "Translite/Backglass",
        cabinetDecals: "Cabinet Decals",
        coinMech: "Coin Mech",
        billAcceptor: "Bill Acceptor",
        cashlessSystem: "Cashless System",
        flipperButtons: "Flipper Buttons",
        launchButtonPlunger: "Launch Button/Plunger",
        coinDoorDiagnostics: "Coin Door Diagnostics",
        creditDisplay: "Credit Display",
        volumeControls: "Volume Controls",
        cabinetSpeakers: "Cabinet Speakers",
        subwoofer: "Subwoofer",
        headphoneJack: "Headphone Jack",
        attractModeLighting: "Attract Mode Lighting",
    },
    operator: {
        modeOperateur: "Mode Opérateur",
        auditStatistiques: "Audit/Statistiques",
        lockSecurises: "Lock Sécurisés",
        eventLogs: "Event Logs",
        firmwareRollback: "Firmware Rollback",
        coolingSystem: "Cooling System",
        easyFuseReplacement: "Easy Fuse Replacement",
        serviceGuides: "Service Guides",
    },
    accessibility: {
        reglageDifficulte: "Réglage de Difficulté",
        modeHandicap: "Mode Handicap",
        sousTitres: "Sous-titres",
        hauteurAjustable: "Hauteur Ajustable",
        modeSilent: "Mode Silent",
    },
    customization: {
        customPlastics: "Custom Plastics",
        playfieldMods: "Playfield Mods",
        customFirmware: "Custom Firmware",
        rgbModding: "RGB Modding",
        alternateRulesets: "Alternate Rulesets",
        customAudioPacks: "Custom Audio Packs",
        physicalMods: "Physical Mods",
        swapOutPlayfields: "Swap-out Playfields",
    },
    premium: {
        upperPlayfield: "Upper Playfield",
        rotatingPlayfield: "Rotating Playfield",
        spinningWheel: "Spinning Wheel",
        hapticFeedback: "Haptic Feedback",
        projectorAr: "Projector AR",
        touchscreenBackglass: "Touchscreen Backglass",
        streamingCamera: "Streaming Camera",
        animatronics: "Animatronics",
    },
    maintenance: {
        selfTestRoutines: "Self-test Routines",
        switchCoilCounters: "Switch/Coil Counters",
        accessPanels: "Access Panels",
        ballCountDiagnostics: "Ball Count Diagnostics",
        serviceModeLog: "Service Mode Logs",
        hotSwapModules: "Hot-swap Modules",
    },
}

export const featureLabelsFr = {
    playfield: {
        flippers: "Flippers",
        popBumpers: "Bumpers Pop",
        slingshots: "Lance-pierres",
        ramps: "Rampes",
        rampsMotorisees: "Rampes Motorisées",
        inlanes: "Couloirs d'entrée",
        outlanes: "Couloirs de sortie",
        standUpTargets: "Cibles debout",
        dropTargets: "Cibles tombantes",
        rockerTargets: "Cibles basculantes",
        spinners: "Spinners",
        captiveBall: "Balle captive",
        kickoutHole: "Trou d'éjection",
        saucers: "Soucoupes",
        scoops: "Ramasseurs",
        ballLock: "Verrouillage de balle",
        diverters: "Déviateurs",
        kickbacks: "Renvois",
        magnets: "Aimants",
        tunnels: "Tunnels",
        skillShotLane: "Couloir de tir de précision",
        plunger: "Lanceur",
        shakerMotor: "Moteur vibreur",
        mechanicalToys: "Jouets mécaniques",
        miniPlayfields: "Mini plateaux",
        dropTargetsEvolutifs: "Cibles tombantes évolutives",
    },
    game_modes: {
        multiball: "Multiball",
        missions: "Missions",
        wizardMode: "Mode Sorcier",
        skillShots: "Tirs de précision",
        combos: "Combos",
        progressionPersistante: "Progression persistante",
        achievements: "Succès",
        difficultyScaling: "Difficulté évolutive",
        timedModes: "Modes chronométrés",
        randomEvents: "Événements aléatoires",
        extraBall: "Balle supplémentaire",
        replay: "Partie gratuite",
        playerProfiles: "Profils joueur",
        challengeMode: "Mode défi",
        tournamentMode: "Mode tournoi",
    },
    visual_feedback: {
        dotMatrixDisplay: "Écran matriciel",
        lcdTftDisplay: "Écran LCD/TFT",
        scoreDisplays: "Afficheurs de score",
        ledInserts: "Inserts LED",
        generalIllumination: "Éclairage général",
        spotlights: "Projecteurs",
        rgbLedsAdressables: "LEDs RGB adressables",
        backglassEclaire: "Fronton éclairé",
        lightShowsSynchronises: "Spectacles lumineux synchronisés",
        hudOverlay: "Interface superposée",
    },
    audio: {
        musique: "Musique",
        voiceSpeech: "Voix/Parole",
        soundEffects: "Effets sonores",
        digitizedSpeech: "Parole numérisée",
        multiChannelAudio: "Audio multicanal",
        dynamicMix: "Mixage dynamique",
        customPlaylists: "Listes de lecture personnalisées",
        reactiveAudio: "Audio réactif",
    },
    electronics: {
        cpuMpuBoard: "Carte CPU/MPU",
        driverBoards: "Cartes de pilotage",
        ioBoards: "Cartes E/S",
        powerSupply: "Alimentation",
        fuseProtection: "Protection fusibles",
        tiltSensor: "Capteur d'inclinaison",
        slamTilt: "Inclinaison brutale",
        switchMatrix: "Matrice de commutateurs",
        opticalSensors: "Capteurs optiques",
        hallSensors: "Capteurs Hall",
        reedSwitches: "Interrupteurs Reed",
        solenoids: "Solénoïdes",
        pwmLeds: "LEDs PWM",
        soundBoard: "Carte son",
        amplificateur: "Amplificateur",
        networkModule: "Module réseau",
        usbSdSlot: "Port USB/SD",
        remoteDiagnostics: "Diagnostics à distance",
        operatorMenu: "Menu opérateur",
        firmwareUpdates: "Mises à jour firmware",
    },
    connectivity: {
        wiFi: "Wi-Fi",
        ethernet: "Ethernet",
        bluetooth: "Bluetooth",
        onlineLeaderboards: "Classements en ligne",
        cloudSaves: "Sauvegardes cloud",
        companionApp: "Application compagnon",
        tournamentModeOnline: "Mode tournoi en ligne",
        apiWebhooks: "API Webhooks",
        streamingFeatures: "Fonctionnalités streaming",
    },
    cabinet: {
        plasticsDecoratifs: "Plastiques décoratifs",
        transliteBackglass: "Translite/Fronton",
        cabinetDecals: "Autocollants caisse",
        coinMech: "Monnayeur",
        billAcceptor: "Accepteur de billets",
        cashlessSystem: "Système sans espèces",
        flipperButtons: "Boutons flippers",
        launchButtonPlunger: "Bouton/Lanceur de lancement",
        coinDoorDiagnostics: "Diagnostics porte-monnaie",
        creditDisplay: "Affichage crédits",
        volumeControls: "Contrôles volume",
        cabinetSpeakers: "Haut-parleurs caisse",
        subwoofer: "Subwoofer",
        headphoneJack: "Prise casque",
        attractModeLighting: "Éclairage mode attraction",
    },
    operator: {
        modeOperateur: "Mode opérateur",
        auditStatistiques: "Audit/Statistiques",
        lockSecurises: "Verrous sécurisés",
        eventLogs: "Journaux d'événements",
        firmwareRollback: "Retour firmware",
        coolingSystem: "Système de refroidissement",
        easyFuseReplacement: "Remplacement fusibles facile",
        serviceGuides: "Guides de service",
    },
    accessibility: {
        reglageDifficulte: "Réglage de difficulté",
        modeHandicap: "Mode handicap",
        sousTitres: "Sous-titres",
        hauteurAjustable: "Hauteur ajustable",
        modeSilent: "Mode silencieux",
    },
    customization: {
        customPlastics: "Plastiques personnalisés",
        playfieldMods: "Modifications plateau",
        customFirmware: "Firmware personnalisé",
        rgbModding: "Modding RGB",
        alternateRulesets: "Règles alternatives",
        customAudioPacks: "Packs audio personnalisés",
        physicalMods: "Modifications physiques",
        swapOutPlayfields: "Plateaux interchangeables",
    },
    premium: {
        upperPlayfield: "Plateau supérieur",
        rotatingPlayfield: "Plateau rotatif",
        spinningWheel: "Roue tournante",
        hapticFeedback: "Retour haptique",
        projectorAr: "Projecteur AR",
        touchscreenBackglass: "Fronton tactile",
        streamingCamera: "Caméra streaming",
        animatronics: "Animatroniques",
    },
    maintenance: {
        selfTestRoutines: "Routines d'auto-test",
        switchCoilCounters: "Compteurs commutateurs/bobines",
        accessPanels: "Panneaux d'accès",
        ballCountDiagnostics: "Diagnostics comptage balles",
        serviceModeLog: "Journaux mode service",
        hotSwapModules: "Modules échangeables à chaud",
    },
}

export const categoryLabels = {
    playfield: "Playfield",
    game_modes: "Game Modes",
    visual_feedback: "Visual Feedback",
    audio: "Audio",
    electronics: "Electronics",
    connectivity: "Connectivity",
    cabinet: "Cabinet",
    operator: "Operator",
    accessibility: "Accessibility",
    customization: "Customization",
    premium: "Premium",
    maintenance: "Maintenance",
}

export const categoryLabelsFr = {
    playfield: "Plateau de jeu",
    game_modes: "Modes de jeu",
    visual_feedback: "Retour visuel",
    audio: "Audio",
    electronics: "Électronique",
    connectivity: "Connectivité",
    cabinet: "Caisse",
    operator: "Opérateur",
    accessibility: "Accessibilité",
    customization: "Personnalisation",
    premium: "Premium",
    maintenance: "Maintenance",
}

export function getFeatureLabels(language: "en" | "fr" = "en") {
    return language === "fr" ? featureLabelsFr : featureLabels
}

export function getCategoryLabels(language: "en" | "fr" = "en") {
    return language === "fr" ? categoryLabelsFr : categoryLabels
}

export type PinballFeatures = {
    [K in keyof typeof featureLabels]: {
        [F in keyof (typeof featureLabels)[K]]: boolean
    }
}

export function createEmptyFeatures(): PinballFeatures {
    const features = {} as PinballFeatures

    Object.keys(featureLabels).forEach((category) => {
        const categoryKey = category as keyof typeof featureLabels
        features[categoryKey] = {} as any

        Object.keys(featureLabels[categoryKey]).forEach((feature) => {
            features[categoryKey][feature as keyof (typeof featureLabels)[typeof categoryKey]] = false
        })
    })

    return features
}
